Repository jenkinsci/saml-plugin, pull requests merged in 2022-01, with the labels that each got.

#157 chore: bump Jenkins core to 2.303.3
  Jenkinsfile
  pom.xml
Labels: dependencies

#158 feat: enable continuous delivery
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: enhancement

#140 Verify the version past the Guava & Guice bumps
  Jenkinsfile
  README.md
Labels: chore
