Repository jenkinsci/saml-plugin, pull requests merged in 2024-10, with the labels that each got.

#445 Upgrade plugin parent POM to latest
  pom.xml
Labels: dependencies, java

#437 docs: [JENKINS-73751] Redirecting to Base URL Rather than Original Requested URL
  doc/TROUBLESHOOTING.md
Labels: documentation

#446 Upgrade to pac4j 6.x, require Java 17 or newer, and migrate to EE 9
  Jenkinsfile
  pom.xml
  src/main/java/org/jenkinsci/plugins/saml/OpenSAMLWrapper.java
  src/main/java/org/jenkinsci/plugins/saml/SamlCrumbExclusion.java
  src/main/java/org/jenkinsci/plugins/saml/SamlProfileWrapper.java
  src/main/java/org/jenkinsci/plugins/saml/SamlRedirectActionWrapper.java
  src/main/java/org/jenkinsci/plugins/saml/SamlSPMetadataWrapper.java
  src/main/java/org/jenkinsci/plugins/saml/SamlSecurityRealm.java
  src/main/java/org/jenkinsci/plugins/saml/SamlValidateIdPMetadata.java
  src/main/java/org/jenkinsci/plugins/saml/user/LoginDetailsProperty.java
  src/main/java/org/jenkinsci/plugins/saml/user/SamlCustomProperty.java
  src/test/java/org/jenkinsci/plugins/saml/FakeRequest.java
  src/test/java/org/jenkinsci/plugins/saml/SamlCrumbExclusionTest.java
Labels: enhancement

#452 fix: [JENKINS-73816] implement missing methods
  src/main/java/org/jenkinsci/plugins/saml/SamlFileResource.java
  src/main/java/org/jenkinsci/plugins/saml/SamlFileResourceCache.java
  src/main/java/org/jenkinsci/plugins/saml/SamlFileResourceDisk.java
Labels: bug
